# Day 6

# Numpy

INDEX

1. Basics
2. Copying an array
3. Joining an array
4. Sorting an array
5. Searching an element from an array

In [2]:
import numpy as np
a = np.array([1,2,3,4])
print(a)
print(type(a))
print(np.__version__)

[1 2 3 4]
<class 'numpy.ndarray'>
1.24.3


In [4]:
import numpy as np
a = np.array(42)
b = np.array([1,2,3,4]) # 1d array
c = np.array([[1,2,3], [4,5,6]]) # 2d array
print(a.ndim)
print(b.ndim)
print(c.ndim)

0
1
2


# 1. Slicing of array

In [6]:
import numpy as np
a = np.array([1,2,3,4,5])
print(a[1:5])
print(a[2:])
print(a[:4])

[2 3 4 5]
[3 4 5]
[1 2 3 4]


# 2.Copy an array

In [9]:
import numpy as np
a = np.array([1,2,3,4])
b = a.copy()
a[0] = 30
print(a)
print(b)

[30  2  3  4]
[1 2 3 4]


# 3.Join 2 array

In [10]:
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])
a1 = np.concatenate((a,b)) #join 2 array using  concatenate()
a2 = np.stack((a,b)) # join 2 array using stack()
a3 = np.hstack((a,b)) # helper function hstack()
print(a1)
print(a2)
print(a3)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


# 4.Sorting an array

In [11]:
import numpy as np
a1 = np.array([1,3,2,5,4])
a2 = np.array([3,6,2,1,4,8])
print(np.sort(a1))
print(np.sort(a2))

[1 2 3 4 5]
[1 2 3 4 6 8]


# 5. Searching from an array

In [12]:
import numpy as np
a1 = np.array([1,5,3,8,0])
x1 = np.where(a1 ==8) # search using where()
x2 = np.where(a1%2 == 0) # find even values in the array
print(a1)
print(x1)
print(x2)


[1 5 3 8 0]
(array([3], dtype=int64),)
(array([3, 4], dtype=int64),)
